# Generated by Django 4.2.24 on 2025-10-16 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0006_patientcase_amount_raised'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('payment_channel', models.CharField(choices=[('mno', 'Mobile Money'), ('bank', 'Bank Transfer'), ('card', 'Card Payment')], default='mno', max_length=20)),
                ('payment_provider', models.CharField(choices=[('Airtel', 'Airtel Money'), ('Tigo', 'Tigo Pesa'), ('Halopesa', 'Halopesa'), ('Azampesa', 'Azampesa'), ('Mpesa', 'M-Pesa'), ('CRDB', 'CRDB Bank'), ('NMB', 'NMB Bank')], default='Mpesa', max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('azampay_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_vendor_id', models.UUIDField(blank=True, null=True)),
                ('payment_partner_id', models.UUIDField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fsp_reference_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_data', models.JSONField(blank=True, default=dict)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='beneficiaries.patientcase')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='donations.donation')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('utility_ref', models.CharField(max_length=128)),
                ('operator', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=128)),
                ('transaction_status', models.CharField(max_length=20)),
                ('submerchant_acc', models.CharField(max_length=100, null=True)),
                ('fsp_reference_id', models.CharField(max_length=128, null=True)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='donations.donation')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['utility_ref'], name='donations_p_utility_b3079e_idx'), models.Index(fields=['reference'], name='donations_p_referen_2615c7_idx'), models.Index(fields=['fsp_reference_id'], name='donations_p_fsp_ref_11c8de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['external_id'], name='donations_d_externa_ff6161_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['azampay_transaction_id'], name='donations_d_azampay_602335_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'),
        ),
    ]
