# Generated by Django 4.2.24 on 2025-10-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_phone_safely'),
        ('users', 'XXXX_remove_phone_safely'),
    ]

    operations = [
    ]
