# Generated by Django 5.2.6 on 2025-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='case_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/images/'),
        ),
    ]
