# Generated by Django 5.2.6 on 2025-09-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_remove_patientcase_hero_image_patientcase_case_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(choices=[('hospital_fees', 'Hospital Fees'), ('medical_staff', 'Medical Staff'), ('medication', 'Medication'), ('supplies', 'Supplies'), ('transport', 'Transport')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
