# Generated by Django 5.2.6 on 2025-09-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_budgetitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='diagnostics',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='notes',
        ),
    ]
