# Generated by Django 4.2.24 on 2025-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_remove_budgetitem_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cases/photos/'),
        ),
    ]
