# Generated by Django 4.2.24 on 2025-10-10 12:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0005_patientcase_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
