# Generated by Django 4.2.24 on 2025-11-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0006_patientcase_amount_raised'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientcase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficiaries.patient'),
        ),
    ]
